# 配置数据库
spring:
  application:
    name: Ethan-System
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/universe
    username: root
    password: 20010731
# 服务器配置
server:
  port: 9000
  servlet:
    context-path: /api